### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [emmahoffman720/first-repository#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by emmahoffman720** [comment]
Thanks for the feedback.  I think i fixed it.  How does it look now?

**Comment by kenmazaika** [comment]
:+1: looks perfect.  Thumbs up.
